### ISSUE TITLE
Should show error if bot haven't add role permission.

### ISSUE THREAD

**Issue by rikusen0335** [Kraigie/nostrum#157]
like so when I use `add_guild_member_role()`, I don't see any error or log.

**Comment by Kraigie** [comment]
You're right that it should show an error, could you show the code in question that you think isn't acting correctly?

**Comment by rikusen0335** [comment]
Okay, here's the code:
```elixir
def handle_event({:GUILD_MEMBER_ADD, {guild_id, member}, _ws_state}) do
  member_id = member.user.id
  Api.add_guild_member_role(@discord_server, member_id, @new_face_permission, nil)
end
```

**Comment by Kraigie** [comment]
What's happening here is that an error is in fact being returned, but you're not acting on it. `Api.add_guild_member_Role/4` is likely returning a tuple in the form of `{:error, <error struct here>}`. If you wish to act on that then you should add some logic to check the result of your API call. This won't appear in your logs or throw an error because it's a return value.

If you want an error to be thrown you should use the bang'd version of the function. Looking now, I see it's one of the only functions in the API module that doesn't have a bang'd version. It should.

You could try your hand at opening a PR to create one, it should be pretty easy. If not I can see that it gets added here pretty quickly.

**Comment by rikusen0335** [comment]
Awww thank you for describe about it! I forgot that _What is Elixir_.
Well don't mind, it's not the bug or any issue! I'm closing this.
