### ISSUE TITLE
Disabling token verification when running in :test env

### ISSUE THREAD

**Issue by lucapasquale** [Kraigie/nostrum#230]
If I try to run the tests on [my bot](https://github.com/lucapasquale/botchini), it throws an error because the token I'm using is invalid. Since it's for testing, I don't want to pass my real discord token, anything I could do to fix this?

![image](https://user-images.githubusercontent.com/15659967/109750879-030a3200-7bbc-11eb-8652-17212a6c377a.png)

**Comment by Andris0** [comment]
If you do not need Nostrum for your tests, you can specify for it to not be started during them
```elixir
# mix.exs
{:nostrum, "~> 0.4", runtime: Mix.env() != :test},
```
```elixir
# application.ex
children = [
  Botchini.Repo,
  {Plug.Cowboy,
   scheme: :http,
   plug: Botchini.Router,
   options: [port: Application.fetch_env!(:botchini, :port)]},
  Botchini.Twitch.AuthMiddleware,
] ++ if Mix.env() != :test, do: [BotchiniDiscord.Consumer], else: []
```

**Comment by lucapasquale** [comment]
It's my first project in elixir, so I didn't know about that. Thanks for the help!

**Comment by jswny** [comment]
Quick follow up to this for anyone else who encounters this. Another way to handle things is to run `mix test --no-start` which doesn't start any applications, instead of the approach above which specifically blacklists Nostrum from running in tests.

 Then in your `test_helper.exs` you can manually start things you actually want running in your tests. For example here's how you would make sure Ecto is running to test that:

```elixir
Application.ensure_all_started(:ecto)

children = [MyApp.Repo]
opts = [strategy: :one_for_one, name: MyApp.TestSupervisor]
Supervisor.start_link(children, opts)

Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, :manual)

ExUnit.start()

```

**Comment by FlXlT** [comment]
> 

The approach by [Andris0](https://github.com/Andris0) is a good solution to the current version of Nostrum.
