### ISSUE TITLE
Error callbacks for Voice play/3

### ISSUE THREAD

**Issue by zastrixarundell** [Kraigie/nostrum#232]
This has been discussed on Discord. Basically when someone calls `Nostrum.Voice.play/3` an `:ok` atom it returned without knowing if the voice command worked or not (at least not with `:ytdl`) without some kind of hacky solution.

One solution might be to pass a fourth optional argument in `play/3` which can either be the `pid` of the caller process or some form of callback. Even a map containing the module and a function name atom and then just use erlang apply. 

Edit: Updated the title. This is more for error handling that just for the music stopping.

**Comment by BrandtHill** [comment]
Because the `youtube-dl` Porcelain process uses `out: :stream` option to pipe input to `ffmpeg`, `Porcelain.Process.await/2` returns `{:error, :noproc}` instead of a `Porcelain.Result.t()` which makes it impossible to determine whether or not `youtube-dl` exited successfully without making some dubious assumptions about how quickly the process exited.

Adding a fifth argument to `play/4` with a module and function seems user-unfriendly. [Events](https://kraigie.github.io/nostrum/Nostrum.Consumer.html#t:voice_speaking_update/0) are already generated when speaking starts and stops.

I've added a field `timed_out` to the [Speaking Update Event](https://kraigie.github.io/nostrum/Nostrum.Struct.Event.SpeakingUpdate.html#t:t/0), which will be set to `true` when the initial `play` timeout occurs, and this can be used to determine that a playing error has occurred. I've also added the config key `:audio_timeout`, `20_000` by default, which can set to a lower value such as `5000` if you intend to pass bad urls to `youtube-dl` and want to be more quickly notified that the `play` invocation has failed.

These changes are live at https://github.com/BrandtHill/nostrum.

**Comment by BrandtHill** [comment]
@zastrixarundell The changes for improved voice error handling are live in master, and you can read about them [here](https://kraigie.github.io/nostrum/Nostrum.Struct.Event.SpeakingUpdate.html#t:timed_out/0) and [here](https://kraigie.github.io/nostrum/voice.html#audio-timeout).

**Comment by jchristgit** [comment]
I will close this for now, feel free to re-open if you feel this does not fix the issue properly.
