### ISSUE TITLE
Dependencies with nostrum ~> 0.4 currently deadlocks versioning

### ISSUE THREAD

**Issue by FlorisXll** [Kraigie/nostrum#330]
Using `{:nostrum, "~> 0.4"}` currently clashes with dependencies `gun` and `cowlib`. 

The latest version 0.5 (`[{:nostrum, github: "Kraigie/nostrum"}]`) is executing `mix deps.get` properly.

Full dependency list:

```
defp deps do
    [
      {:phoenix, "~> 1.5.13"},
      {:phoenix_ecto, "~> 4.4"},
      {:ecto_sql, "~> 3.4"},
      {:postgrex, ">= 0.0.0"},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},
      {:mix_test_watch, "~> 1.0", only: :dev, runtime: false},
      {:nostrum, github: "Kraigie/nostrum"}
    ]
end

**Comment by jchristgit** [comment]
Thanks for reporting this. I think it's the same issue as #236 (see #240) where we upgraded the `gun` dependency (which also upgraded `cowlib`, as far as I remember).

We currently can't do a new hex release as our `gun` dependency is a release candidate, and we are waiting for a new 2.0 release (see https://github.com/ninenines/gun/issues/268). Some workarounds have been presented for this, I will bring this up again with the maintainers.

That said, we can't release a new 0.4 version either due to the mentioned versioning issue, so the only workaround as of now is to use the Git version until 0.5 is out.
